// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3uD2t5L8gg5c9QszslsO9FfymdNiSa4Q',
    appId: '1:456795898989:web:28524ce2432a7102b1ab64',
    messagingSenderId: '456795898989',
    projectId: 'ev-charging-2f2d2',
    authDomain: 'ev-charging-2f2d2.firebaseapp.com',
    storageBucket: 'ev-charging-2f2d2.appspot.com',
    measurementId: 'G-2V9YY4LW80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQK3WcZ7irVGkrdLoCcdVS9Q1J29CCG9M',
    appId: '1:456795898989:android:7732d60b1ede476bb1ab64',
    messagingSenderId: '456795898989',
    projectId: 'ev-charging-2f2d2',
    storageBucket: 'ev-charging-2f2d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjy7x_kTaDlNLWODIkRRV4yaaCSHVL26s',
    appId: '1:456795898989:ios:eb46173059f2b83eb1ab64',
    messagingSenderId: '456795898989',
    projectId: 'ev-charging-2f2d2',
    storageBucket: 'ev-charging-2f2d2.appspot.com',
    iosBundleId: 'com.example.evCharging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjy7x_kTaDlNLWODIkRRV4yaaCSHVL26s',
    appId: '1:456795898989:ios:c8765020ab0c5842b1ab64',
    messagingSenderId: '456795898989',
    projectId: 'ev-charging-2f2d2',
    storageBucket: 'ev-charging-2f2d2.appspot.com',
    iosBundleId: 'com.example.evCharging.RunnerTests',
  );
}
